/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface IconAdd {
        /**
          * 图标颜色
         */
        "color": string;
        /**
          * 图标大小
         */
        "size": number;
        /**
          * 图标线条宽度
         */
        "strokeWidth": number;
    }
    interface IconDelete {
        /**
          * 图标颜色
         */
        "color": string;
        /**
          * 图标大小
         */
        "size": number;
        /**
          * 图标线条宽度
         */
        "strokeWidth": number;
    }
}
declare global {
    interface HTMLIconAddElement extends Components.IconAdd, HTMLStencilElement {
    }
    var HTMLIconAddElement: {
        prototype: HTMLIconAddElement;
        new (): HTMLIconAddElement;
    };
    interface HTMLIconDeleteElement extends Components.IconDelete, HTMLStencilElement {
    }
    var HTMLIconDeleteElement: {
        prototype: HTMLIconDeleteElement;
        new (): HTMLIconDeleteElement;
    };
    interface HTMLElementTagNameMap {
        "icon-add": HTMLIconAddElement;
        "icon-delete": HTMLIconDeleteElement;
    }
}
declare namespace LocalJSX {
    interface IconAdd {
        /**
          * 图标颜色
         */
        "color"?: string;
        /**
          * 图标大小
         */
        "size"?: number;
        /**
          * 图标线条宽度
         */
        "strokeWidth"?: number;
    }
    interface IconDelete {
        /**
          * 图标颜色
         */
        "color"?: string;
        /**
          * 图标大小
         */
        "size"?: number;
        /**
          * 图标线条宽度
         */
        "strokeWidth"?: number;
    }
    interface IntrinsicElements {
        "icon-add": IconAdd;
        "icon-delete": IconDelete;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "icon-add": LocalJSX.IconAdd & JSXBase.HTMLAttributes<HTMLIconAddElement>;
            "icon-delete": LocalJSX.IconDelete & JSXBase.HTMLAttributes<HTMLIconDeleteElement>;
        }
    }
}
